### ISSUE TITLE
HasTrailingLineBreak and HasTrailingLineBreakInString return wrong results

### ISSUE THREAD

**Issue by xanni** [rivo/uniseg#49]
The wrong constants are tested in line.go:

`return property == lbBK || property == lbCR || property == lbLF || property == lbNL`

should be

`return property == prBK || property == prCR || property == prLF || property == prNL`

as defined in properties.go

This is where go needs better type safety.

**Comment by xanni** [comment]
I see this has already been fixed but not released.  Is there a reason there is no 0.4.5 release incorporating the fix?

**Comment by rivo** [comment]
Well, I just keep forgetting it. Basically, I have to tag every single commit now. And since some commits (e.g. this one) are pull requests from other people, hitting the <kbd>Merge</kbd> button isn't enough anymore. Now I also have to look up the new version, then `git pull origin master`, `git tag vX.Y`, and `git push origin --tags`.

I have resisted this in `tview` for a long time, see https://github.com/rivo/tview/issues/788 for a discussion.

With `uniseg`, I don't expect so many commits so I was ok with introducing semver tags. But as you can see, this introduces problems.

As with `tview`, I would suggest to always get the latest commit of `uniseg` instead of relying on version tags.

ps. I added a tag just now.

**Comment by xanni** [comment]
Yes, that's what I did to make my code work.  Maybe you should update the "Installation" section of the documentation to `go get github.com/rivo/uniseg@master` instead of just `go get github.com/rivo/uniseg` which will get the last released version, not the latest commit as you recommend.
